### ISSUE TITLE
Create a component for use-cases

### ISSUE THREAD

**Issue by AlexikM** [CondensationDS/Condensation-Website#26]
In the page of use-cases, display a big text with 3 images for each use-case as defined in the mockups. 

![image](https://user-images.githubusercontent.com/55086364/155786312-c1c601a7-3ba9-40b9-92b8-9cc712ebb343.png)
![image](https://user-images.githubusercontent.com/55086364/155786452-3f9b2be2-43b0-48dd-bcf0-bd8412c37a30.png)

**Comment by AlexikM** [comment]
@CharlineLavigne do you want to take this one?

**Comment by CharlineLavigne** [comment]
Suure, I'm on it

**Comment by CharlineLavigne** [comment]
The issue is not finished completely, only the big screen version was done and it's not responsive. Here's the follow up ticket for completing the whole task : https://github.com/CondensationDS/Condensation-Website/issues/43
